---

- name: update lab inventory
  hosts: all
  connection: local
  become: yes

  tasks:

  - name: Template out new inventory
    template:
      src: /tmp/inventory.j2
      dest: /tmp/new_inv
    run_once: true
